---
# tasks file for setup_transmission
  - name: Update APT Cache
    apt:
      update_cache: yes

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - transmission-common 
      - transmission-daemon 


  - name: Create Mount Points
    file: path={{ download-dir }} state=directory owner={{ transmission-user }} group={{ transmission-group }} mode=0777

  - name: Create Mount Points
    file: path={{ download-dir }}/Incomplete state=directory owner={{ transmission-user }} group={{ transmission-group }} mode=0777
  
  - name: stop Transmission
    command: systemctl stop transmission-daemon.service

  - template: src="settings.json.j2" dest="/var/lib/transmission-daemon/.config/transmission-daemon/settings.json" owner="{{ transmission-user }}" group="{{ transmission-group }}" mode="0755"

  - name: Start Transmission
    command: systemctl start transmission-daemon.service
